#!/usr/bin/env python3
import sys
import re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
branch = branch.decode("utf-8")
issue_regex = '^(?P<issue>(regex-of-branch-to-append-to-comit_msg)-\d+)'
if re.match(issue_regex, branch):
    issue = re.match(issue_regex, branch).group('issue')
    with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        fh.seek(0, 0)
        fh.write('%s %s' % (issue, commit_msg))
elif branch != 'master' and branch != 'dev':
    print('Incorrect branch name')
    sys.exit(1)
